name: PR Validator

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Format check
        run: cargo fmt  -- --check
      - name: Build and Lint
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose
